version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          DOCKER_USER=sergejss
          DOCKER_PASS=maijajulija
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   wunderio/circleci-builder:$TAG . 
          docker login -u $DOCKER_USER -p $DOCKER_PASS   
          docker push wunderio/circleci-builder:$TAG


